//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatroHRIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class tblClientDetail
    {
        public tblClientDetail()
        {
            this.tblProjectDetails = new HashSet<tblProjectDetail>();
            this.tblTimeSheets = new HashSet<tblTimeSheet>();
        }
    
        public int intClientID { get; set; }
        [Required(ErrorMessage = "Please enter name!!")]
        [Display(Name = "Name")]    
        public string varClientName { get; set; }
        [Required(ErrorMessage = "Please enter email address!!")]
        [Display(Name = "Email Id")]
        public string varClientEmailID { get; set; }
         [Display(Name = "Description")]
        public string varClientDescription { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
        [Required(ErrorMessage = "Please enter phone no!!")]
        [RegularExpression("^[0-9]{10}$", ErrorMessage = "Please enter valid phone number!!")]
        [DataType(DataType.PhoneNumber)]
        public string varClientPhoneNo { get; set; }
        [Required(ErrorMessage = "Please enter address!!")]
        [Display(Name = "Address")]    
        public string varClientAddress { get; set; }
    
        public virtual ICollection<tblProjectDetail> tblProjectDetails { get; set; }
        public virtual ICollection<tblTimeSheet> tblTimeSheets { get; set; }
    }
}
