//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatroHRIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGoalTitle
    {
        public tblGoalTitle()
        {
            this.tblEmployeeGoals = new HashSet<tblEmployeeGoal>();
        }
    
        public int intTilteID { get; set; }
        public string varTitleName { get; set; }
        public string varTitleDesc { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<int> intUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
    
        public virtual ICollection<tblEmployeeGoal> tblEmployeeGoals { get; set; }
    }
}
