//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatroHRIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class tblProjectDetail
    {
        public tblProjectDetail()
        {
            this.tblTimeSheets = new HashSet<tblTimeSheet>();
        }
    
        public int intProjectID { get; set; }
        [Required(ErrorMessage = "Project Name is Compulsory!!")]
        [Display(Name = "Project Name")]
        public string varProjectName { get; set; }
        [Required(ErrorMessage = "Internal Project Head is Compulsory!!")]
        [Display(Name = "Internal Project Head")]
        public Nullable<int> intInternalProjectHead { get; set; }
         [Display(Name = "Project Description")]
        public string varProjectDescription { get; set; }
         [Required(ErrorMessage = "Start Date is Compulsory!!")]
         [Display(Name = "Start Date")]
        public Nullable<System.DateTime> dtProjectStartDate { get; set; }
         [Required(ErrorMessage = "End Date is Compulsory!!")]
         [Display(Name = "End Date")]
        public Nullable<System.DateTime> dtProjectEndDate { get; set; }
        [Display(Name = "Project Status")]
        public Nullable<int> intProjectStatus { get; set; }
        [Display(Name = "Client Name")]
        public Nullable<int> intClientID { get; set; }
        [Required(ErrorMessage = "External Project Head is Compulsory!!")]
        [Display(Name = "External Project Head")]
        public string varClientProjectHead { get; set; }
        [Display(Name = "Project Team")]
        public string varTeamMemDetails { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
         [Display(Name = "Completion (Approx.%)")]
        public Nullable<int> intCompletionID { get; set; }
    
        public virtual tblClientDetail tblClientDetail { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual ICollection<tblTimeSheet> tblTimeSheets { get; set; }
        public virtual tblCompletion tblCompletion { get; set; }
    }
}
