//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatroHRIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatus
    {
        public tblStatus()
        {
            this.tblProjectDetails = new HashSet<tblProjectDetail>();
            this.tblEmployeeGoals = new HashSet<tblEmployeeGoal>();
        }
    
        public int intStatusID { get; set; }
        public string varStatus { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
    
        public virtual ICollection<tblProjectDetail> tblProjectDetails { get; set; }
        public virtual ICollection<tblEmployeeGoal> tblEmployeeGoals { get; set; }
    }
}
